<script lang="ts">
import axios from 'axios';
  import { clientDataMapping, clientURL, itemURL, productDataMapping, setting, template, terms, variables } from '../store/SettingsStore';

export const baseURL = 'http://127.0.0.1:5000'

const instance = axios.create({
  baseURL
});

instance.interceptors.request.use(config => {
  const token = localStorage.getItem('token'); 
  if (token) {
    config.headers['Authorization'] = `Bearer ${token}`;
  }
  return config;
}, error => {
  return Promise.reject(error);
});


export const getData = (endpoint:string) => {
  return instance.get(endpoint)
    .then(response => {
        const data = response.data ;
        data['status'] = response.status ;
        return data ;
    })
    .catch(error => {
      if(error.response) {
        console.error(error);
        return {...error.response.data,'status':error.response.status}
      }
      throw error;
    });
};

export const postData = (endpoint:string, data:any,headers?:any) => {
  return instance.post(endpoint, data,headers)
    .then(response => {
        const data = response.data ;
        data['status'] = response.status ;
        return data;
    })
    .catch(error => {
      if(error.response) {
        return {...error.response.data,'status':error.response.status}
      }
      throw error;
    });
};

export const postForm = () => {

  postData('/forms',{
      "formNo": "string - Generated By Backend",
      "_id": "string - Generated by Backend",
      "createddate": "date - Generated by Backend",
      "modifieddate": "date - Generated by Backend",
      "templateId":"string",
      "templateName":"string",
      "recordInformation": {
          "recordName": "string",
          "recordData": [
              {
                  "key": "string - field Name",
                  "value": "string - value given",
                  "type": "string - type of the field (number, string, date)"
              },
              {
                  "key": "string",
                  "value": "string",
                  "type": "string"
              },
              {
                  "key": "string",
                  "value": "string",
                  "type": "string"
              }
          ]
      },
      "clientInformation": [
          {
              "key": "string",
              "value": "string",
              "type": "string"
          },
          {
              "key": "string",
              "value": "string",
              "type": "string"
          },
          {
              "key": "string",
              "value": "string",
              "type": "string"
          }
      ],
      "itemDetails": [
          {
              "item": "string",
              "type": "string",
              "qty": "number",
              "price": "number",
              "discount": {
                  "value": "number",
                  "type": "string - percentage or rupees"
              },
              "GST": "number",
              "total": "number",
              "thumbnail": "Array<string>",
              "description": "string",
              "itemId": "string",
              "_id": "string"
  
          },
          {
              "item": "string",
              "type": "string",
              "qty": "number",
              "price": "number",
              "discount": {
                  "value": "number",
                  "type": "string - percentage or rupees"
              },
              "GST": "number",
              "total": "number",
              "thumbnail": "Array<string>",
              "description": "string",
              "itemId": "string",
              "_id": "string"
  
          }
      ],
      "price": {
          "totalDiscount":[
              {
                  "key": "string",
                  "value": "number",
                  "type": "string"
              },
              {
                  "key": "string",
                  "value": "number",
                  "type": "string"
              }
          ],
          "extraCharge":{
              "value": "number",
              "type": "string"
          },
          "additionalCharges":[{
              "value": "number",
              "type": "string"
          }],
          "totalAmount": "number"
      },
      "invoiceInfo": {
          "signature": "string",
          "addtionalInfo": "string",
          "additionalAttachments": "Array<string>",
          "termsConditions": "Array<string",
          "saveTermsConditions": "boolean"
      }
  
  })
}

export const postSetting = () => {

  postData('/setting',{
    "_id": "string",
    "templateName": $template.name,
    "createddate": "date",
    "modifieddate": "date",
    "businessName": $template.business,
    "otherInfo": $template.other,
    "settings": {
        "themeName": "string",
        "includeDiscount": $setting.discount,
        "includeGST": $setting.GST,
        "includeItemDescription": $setting.description,
        "includeAdditionalNotes": $setting.additionalNotes,
        "includeAttachments": $setting.attachments
    },
    "customVariables":$variables.map(x =>{
        return {
            "variableName": x.name,
            "variableValues": x.values,
        }
    })
    ,
    "dataMapping":{
        "clientInformation": {
            "dataUrl": $itemURL,
            "isAuthRequired": false,
            "authDetails": {},
            "mappedData": $clientDataMapping.map(x => {
                return {
                    "urlFieldName": x.from,
                    "templateFieldName": x.to,
                    "type": "string"
                }
            })
        },
        "itemMapping": {
            "dataUrl": $clientURL,
            "isAuthRequired": "boolean",
            "authDetails": {},
            "mappedData": $productDataMapping.map(x => {
                return {
                    "urlFieldName": x.from,
                    "templateFieldName": x.to,
                    "type": "string"
                }
            })
        },
        "terms": $terms.map((x,y) => {
            return {
                value:x,
                order:y,
            }
        })
    }
})
}
</script>